version: '3.4'

networks:
  backend:
    driver: bridge

services:
  customerdb:
    container_name: customer-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=password_test123
    networks:
      - backend
    ports:
      - 18001:1433

  customermicroservice:
    container_name: customer-ms
    image: ${DOCKER_REGISTRY-}customermicroservice
    build:
      context: .
      dockerfile: CustomerMicroService/Dockerfile
    networks:
      - backend
    ports:
      - 8002:8080
    environment:
      - DB_HOST=customerdb
      - DB_USER=sa
      - DB_NAME=customer_db
      - DB_SA_PASSWORD=password_test123
